"use strict";
let nums1 = 10;
let nums2 = 5;
let nums3;
nums3 = nums1 + nums2;
console.log("Addition result:", nums3);
nums3 = nums1 - nums2;
console.log("Subtraction result:", nums3);
nums3 = nums1 * nums2;
console.log("Multiplication result:", nums3);
nums3 = nums1 / nums2;
console.log("Division result:", nums3);
nums1 = Number("10");
nums2 = Number(true);
nums3 = nums1 + nums2;
console.log("Addition result with type change:", nums3);
nums3 = nums1 - nums2;
console.log("Subtraction result with type change:", nums3);
nums3 = nums1 * nums2;
console.log("Multiplication result with type change:", nums3);
nums3 = nums1 / nums2;
console.log("Division result with type change:", nums3);
